name: Issue Screening

on:
  issues:
    types: [opened, edited]

jobs:
  screen-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get details and check for keywords
        id: issue_check
        uses: actions/github-script@v5
        with:
          script: |
            const issue = context.payload.issue;
            const issueNumber = issue.number;
            const title = (issue.title || "").toLowerCase();
            const body = (issue.body || "").toLowerCase();
            core.setOutput('number', issueNumber);

            const keywords = ["star", "stars", "unusual", "activity", "spam", "badword", "inappropriate"];
            let containsKeyword = false;

            console.log(`Checking issue #${issueNumber} for keywords...`);
            for (const keyword of keywords) {
              if (title.includes(keyword) || body.includes(keyword)) {
                containsKeyword = true;
                console.log(`Keyword '${keyword}' found in issue #${issueNumber}.`);
                break;
              }
            }

            console.log(`Keyword check for issue #${issueNumber} completed. contains_keyword=${containsKeyword}`);
            core.setOutput('contains_keyword', containsKeyword);

      - name: Close issue if it contains keywords
        if: steps.issue_check.outputs.contains_keyword == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.ISSUE }}
          script: |
            const issueNumber = ${{ steps.issue_check.outputs.number }};
            try {
              console.log(`Attempting to close issue #${issueNumber} due to keyword.`);
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                state: 'closed'
              });
              console.log(`Successfully closed issue #${issueNumber}.`);
            } catch (error) {
              console.error(`Failed to close issue #${issueNumber}:`, error);
              throw error;
            }
